name: lighthouse
on:
  issue_comment:
    types: [edited]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Preview URL
        id: capture_preview_url
        uses: aaimio/vercel-preview-url-action@b82a318e4c1eac7ef38ed1b241677a81db08494b # v2.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Redirect URL
        id: get_redirected_url
        run: |
          PREVIEW_URL="${{ steps.capture_preview_url.outputs.vercel_preview_url }}"
          # shellcheck disable=SC1083
          REDIRECTED_URL=$(curl -Ls -o /dev/null -w %{url_effective} "$PREVIEW_URL")
          echo "REDIRECTED_URL=$REDIRECTED_URL" >> "$GITHUB_OUTPUT"

      - name: Generate Lighthouse report
        id: lighthouse_audit
        uses: treosh/lighthouse-ci-action@fcd65974f7c4c2bf0ee9d09b84d2489183c29726 # 12.6.1
        env:
          REDIRECTED_URL_BASE: ${{ steps.get_redirected_url.outputs.REDIRECTED_URL }}
          REDIRECTED_URL_ABOUT: ${{ steps.get_redirected_url.outputs.REDIRECTED_URL }}${{'about'}}
          REDIRECTED_URL_PAGE: ${{ steps.get_redirected_url.outputs.REDIRECTED_URL }}${{'page/zsh-completion'}}
        with:
          urls: |
            $REDIRECTED_URL_BASE
            $REDIRECTED_URL_ABOUT
            $REDIRECTED_URL_PAGE
          temporaryPublicStorage: true

      - name: Format score
        id: format_lighthouse_score
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const results = ${{ steps.lighthouse_audit.outputs.manifest }};
            const links = ${{ steps.lighthouse_audit.outputs.links }}
            const comments = results
              .map((result, index) => {
                const formatResult = (res) => Math.round(res * 100);

                const score = (res) => (res >= 90 ? '🟢' : res >= 50 ? '🟠' : '🔴');

                const performance = formatResult(result.summary.performance);
                const accessibility = formatResult(result.summary.accessibility);
                const bestPractices = formatResult(result.summary['best-practices']);
                const seo = formatResult(result.summary.seo);

                const comment = [
                  `⚡️ [Lighthouse report](${
                    Object.values(links)[index]
                  }) for the changes in this PR:`,
                  '| Category | Score |',
                  '| --- | --- |',
                  `| ${score(performance)} Performance | ${performance} |`,
                  `| ${score(accessibility)} Accessibility | ${accessibility} |`,
                  `| ${score(bestPractices)} Best practices | ${bestPractices} |`,
                  `| ${score(seo)} SEO | ${seo} |`,
                  ' ',
                  `* Lighthouse ran on [${Object.keys(links)[index]}](${
                    Object.keys(links)[index]
                  })`,
                  '',
                ].join('\n');
                return comment;
              })
              .join('\n\n');

            core.setOutput("comment", comments);

      - name: Comment Lighthouse Score
        id: comment_to_pr
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.issue.number }}
          header: lighthouse
          message: |
            ${{ steps.format_lighthouse_score.outputs.comment }}
