name: lint
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Cache Dependencies
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint:es

      - name: StyleLint
        run: npm run lint:style

      - name: MarkupLint
        run: npm run lint:markup

      - name: Check Format
        run: npm run format:check
