name: pa11y
on:
  issue_comment:
    types: [edited]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Get Preview URL
        id: capture_preview_url
        uses: aaimio/vercel-preview-url-action@b82a318e4c1eac7ef38ed1b241677a81db08494b # v2.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Redirect URL
        id: get_redirected_url
        run: |
          PREVIEW_URL="${{ steps.capture_preview_url.outputs.vercel_preview_url }}"
          # shellcheck disable=1083
          REDIRECTED_URL=$(curl -Ls -o /dev/null -w %{url_effective} "$PREVIEW_URL" | sed 's/\/$//')
          echo "REDIRECTED_URL=$REDIRECTED_URL" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm install -g pa11y-ci

      - name: pa11y-ci
        env:
          REDIRECTED_URL: ${{ steps.get_redirected_url.outputs.REDIRECTED_URL }}
          REDIRECTED_SITEMAP: ${{ steps.get_redirected_url.outputs.REDIRECTED_URL }}${{'/sitemap.xml'}}
          REDIRECTED_RSS: ${{ steps.get_redirected_url.outputs.REDIRECTED_URL }}${{'/rss.xml'}}
          REPLACE_BASE_URL: ' https://blog.syufu.dev'
        run: |
          pa11y-ci --config .pa11yci.json --sitemap "$REDIRECTED_SITEMAP" --sitemap-find "$REPLACE_BASE_URL" --sitemap-replace "$REDIRECTED_URL"
